import asyncio
import logging
import os
import sys

from src.config import configure_logging
from src.database.models.artifact import Artifact
from src.database.models.conversation import Conversation
from src.database.models.message import Message
from src.database.models.user import User
from src.database.mongo import async_mongo_manager
from src.services.agents.core.interceptors import ErrorLoggingInterceptor
from src.services.agents.graphs_bundle import graphs_base_module
from src.services.mcp.artifact_context import (
    reset_artifact_context,
    set_artifact_context,
)
from src.services.mcp.artifact_ingestion import ArtifactInterceptor

configure_logging()
logger = logging.getLogger(__name__)

DUMMY_MCP_HOST = os.environ.get("E2E_DUMMY_MCP_HOST", "dummy-mcp")
DUMMY_MCP_PORT = int(os.environ.get("E2E_DUMMY_MCP_PORT", "8000"))
DUMMY_MCP_URL = f"http://{DUMMY_MCP_HOST}:{DUMMY_MCP_PORT}/mcp"

DEMO_QUESTION = "Show me a sample satellite image and the acquisition report"


def _block_text(tool_result) -> str:
    """Extract the text of the first content block of a LangChain tool result."""
    if isinstance(tool_result, list) and tool_result:
        block = tool_result[0]
        if isinstance(block, dict) and "text" in block:
            return str(block["text"])
    return str(tool_result)


async def seed_demo_artifacts(email: str) -> None:
    """Seed a demo conversation for `email` with real MCP-generated artifacts.

    Calls the dummy-mcp server's tools through the SAME interceptor stack the
    agentic runner uses (see tests/e2e/test_artifact_e2e.py), so the persisted
    Artifacts and the assistant message stubs are exactly what a production
    MCP tool call would produce — only the LLM narration around them is canned.
    """
    from langchain_mcp_adapters.client import MultiServerMCPClient

    await async_mongo_manager.connect()

    user = await User.find_one({"email": email})
    if not user:
        print(f"No user with email {email} — create one with src.commands.create_user")
        sys.exit(1)

    latency_interceptor_cls = graphs_base_module().LatencyInterceptor
    artifact_interceptor = ArtifactInterceptor()
    # Hold `client` for the whole run: the tool wrappers don't keep a strong
    # reference to it and the interceptor only holds a weakref.
    client = MultiServerMCPClient(
        {"dummy": {"transport": "streamable_http", "url": DUMMY_MCP_URL, "headers": {}}},
        tool_name_prefix=True,
        tool_interceptors=[
            latency_interceptor_cls(),
            ErrorLoggingInterceptor(),
            artifact_interceptor,
        ],
    )
    artifact_interceptor.bind_client(client)
    tools = {t.name: t for t in await client.get_tools(server_name="dummy")}

    conversation = await Conversation.create(
        user_id=user.id, name="Demo: MCP artifacts"
    )

    ctx, token = set_artifact_context(
        user_id=user.id, conversation_id=conversation.id
    )
    try:
        image_result = await tools["dummy_get_sample_image"].ainvoke({"color": "blue"})
        report_result = await tools["dummy_get_sample_report"].ainvoke({})
        text_result = await tools["dummy_get_text_summary"].ainvoke({})
    finally:
        reset_artifact_context(token)

    if not ctx.collected_artifact_ids:
        print(
            "No artifacts were captured — is the dummy-mcp service up? "
            "(docker compose up -d dummy-mcp)"
        )
        sys.exit(1)

    output = "\n\n".join(
        [
            "Here is the sample satellite image generated by the MCP tool:",
            _block_text(image_result),
            "The acquisition report is available as a downloadable file:",
            _block_text(report_result),
            _block_text(text_result),
        ]
    )
    message = await Message.create(
        conversation_id=conversation.id,
        input=DEMO_QUESTION,
        output=output,
        artifact_ids=list(ctx.collected_artifact_ids),
    )

    # The interceptor ran before the Message existed; backfill the linkage.
    for artifact_id in ctx.collected_artifact_ids:
        artifact = await Artifact.find_by_id(artifact_id)
        if artifact:
            artifact.message_id = message.id
            await artifact.save()

    logger.info(
        f"Seeded conversation {conversation.id} with "
        f"{len(ctx.collected_artifact_ids)} MCP artifacts for {email}"
    )
    print(f"Conversation: {conversation.id}")
    print(f"Message: {message.id}")
    print(f"Artifacts: {', '.join(ctx.collected_artifact_ids)}")
    print(f"Open http://localhost:5173/chat/{conversation.id} after logging in as {email}")


if __name__ == "__main__":
    USAGE = "Usage: python -m src.commands.seed_demo_artifacts <email>"

    if len(sys.argv) != 2 or not sys.argv[1]:
        print(USAGE)
        sys.exit(1)

    asyncio.run(seed_demo_artifacts(sys.argv[1]))
