"""Dummy MCP server for artifact-ingestion e2e testing.

Exposes tools exercising the block types ArtifactInterceptor cares about,
without needing an LLM or any real upstream service:

- get_sample_image: returns ImageContent directly (a tiny, dependency-free
  hand-encoded PNG — no Pillow, just stdlib zlib/struct).
- get_sample_report: returns a ResourceLink pointing at a CSV exposed via
  @mcp.resource, exercising the resources/read fetch path.
- get_text_summary: returns plain text (control case — must pass through
  the interceptor untouched).
- compute_metrics: the reference fix for "effis-style" tools — see its
  docstring below.

Mirrors the eve-esa/mcp-tool-registry FastMCP conventions (streamable-http
transport, stateless_http=True) so it doubles as a stand-in for the retired
dummy_image test server.
"""

import base64
import os
import struct
import tempfile
import zlib

from mcp.server.fastmcp import FastMCP
from mcp.types import ImageContent, ResourceLink, TextContent

mcp = FastMCP(
    "Dummy Artifact Server",
    host="0.0.0.0",
    port=8000,
    stateless_http=True,
)

# ─── Tiny dependency-free PNG encoder (stdlib zlib/struct only) ───────────────

_COLORS = {
    "blue": (30, 80, 220),
    "red": (200, 30, 30),
    "green": (30, 180, 60),
    "yellow": (230, 200, 30),
}


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def make_solid_png(width: int, height: int, rgb: tuple[int, int, int]) -> bytes:
    """Encode a solid-color RGB PNG using only the standard library."""
    signature = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    row = b"\x00" + bytes(rgb) * width  # filter byte 0 (none) + RGB pixels
    raw = row * height
    idat = zlib.compress(raw, 9)
    return (
        signature
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", idat)
        + _png_chunk(b"IEND", b"")
    )


# ─── Resource backing get_sample_report's ResourceLink ────────────────────────

SAMPLE_CSV = "id,label,value\n1,alpha,10\n2,beta,20\n3,gamma,30\n"
SAMPLE_CSV_URI = "resource://dummy/sample-report.csv"


@mcp.resource(SAMPLE_CSV_URI, mime_type="text/csv")
def sample_report_resource() -> str:
    """Backing resource for the ResourceLink returned by get_sample_report."""
    return SAMPLE_CSV


# ─── Tools ─────────────────────────────────────────────────────────────────────


@mcp.tool()
def get_sample_image(color: str = "blue") -> ImageContent:
    """Return a tiny 64x64 solid-color PNG as inline ImageContent."""
    rgb = _COLORS.get(color.lower(), _COLORS["blue"])
    png_bytes = make_solid_png(64, 64, rgb)
    data = base64.b64encode(png_bytes).decode("ascii")
    return ImageContent(type="image", data=data, mimeType="image/png")


@mcp.tool()
def get_sample_report() -> ResourceLink:
    """Return a ResourceLink to a small CSV report, fetched via resources/read."""
    return ResourceLink(
        type="resource_link",
        name="sample-report.csv",
        uri=SAMPLE_CSV_URI,
        mimeType="text/csv",
        description="A tiny CSV report generated by the dummy MCP server",
    )


@mcp.tool()
def get_text_summary() -> str:
    """Return plain text with no attachments (control case: must pass through)."""
    return "This is a plain text summary with no attachments."


# ─── compute_metrics: reference fix for "effis-style" tools ───────────────────
#
# Some real MCP tools (e.g. the mcp-tool-registry's `effis`) compute a result,
# write it to a file on the container's ephemeral filesystem, and return
# nothing that captures the file itself — just a path or a description. That
# path is meaningless to any MCP client: it lives inside a container that may
# already be gone by the time the client tries to read it, and no client has
# filesystem access to the server's container anyway. The fix is server-side:
# write the file, then expose it as an MCP resource and return a
# ResourceLink to it, exactly like get_sample_report does for its CSV. This
# tool is the reference implementation of that fix for the mcp-tool-registry
# coordination doc (docs/mcp-file-return-convention.md).

_METRICS_DIR = tempfile.mkdtemp(prefix="dummy-mcp-metrics-")


def _metrics_png_path(filename: str) -> str:
    # filename comes from a resource URI segment; os.path.basename keeps the
    # path confined to _METRICS_DIR regardless of what's passed in.
    return os.path.join(_METRICS_DIR, os.path.basename(filename))


@mcp.resource("resource://dummy/compute-metrics/{filename}", mime_type="image/png")
def compute_metrics_resource(filename: str) -> bytes:
    """Backing resource for the ResourceLink returned by compute_metrics.

    Reads back the PNG that compute_metrics wrote to the container's temp
    dir, so the file becomes reachable via resources/read instead of being
    stranded on the ephemeral filesystem. ``filename`` is also what
    ArtifactInterceptor derives the persisted artifact's display filename
    from (the URI's last path segment), so it matches what compute_metrics
    named the file on disk.
    """
    with open(_metrics_png_path(filename), "rb") as f:
        return f.read()


@mcp.tool()
def compute_metrics(region: str = "demo") -> list:
    """Compute a metrics chart for a region and expose it as a ResourceLink.

    This is the reference fix for "effis-style" tools: instead of writing a
    chart-like file to the container's ephemeral filesystem and returning
    only a path or a bare summary (invisible to any MCP client), it writes
    the file, registers it as an MCP resource (see compute_metrics_resource
    above), and returns a ResourceLink alongside a short text summary. EVE's
    ArtifactInterceptor resolves the ResourceLink via resources/read and
    persists it as an Artifact — see
    src/services/mcp/artifact_ingestion.py.
    """
    rgb = _COLORS.get("green")
    png_bytes = make_solid_png(48, 48, rgb)
    resource_filename = f"metrics-{region}.png"
    with open(_metrics_png_path(resource_filename), "wb") as f:
        f.write(png_bytes)

    return [
        TextContent(
            type="text",
            text=f"Computed metrics for region={region!r}: mean=42.0, std=3.1",
        ),
        ResourceLink(
            type="resource_link",
            name=resource_filename,
            uri=f"resource://dummy/compute-metrics/{resource_filename}",
            mimeType="image/png",
            description=f"Metrics chart for region={region!r}, generated by compute_metrics",
        ),
    ]


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
