"""Dummy MCP server for artifact-ingestion e2e testing.

Exposes three tools exercising the three block types ArtifactInterceptor cares
about, without needing an LLM or any real upstream service:

- get_sample_image: returns ImageContent directly (a tiny, dependency-free
  hand-encoded PNG — no Pillow, just stdlib zlib/struct).
- get_sample_report: returns a ResourceLink pointing at a CSV exposed via
  @mcp.resource, exercising the resources/read fetch path.
- get_text_summary: returns plain text (control case — must pass through
  the interceptor untouched).

Mirrors the eve-esa/mcp-tool-registry FastMCP conventions (streamable-http
transport, stateless_http=True) so it doubles as a stand-in for the retired
dummy_image test server.
"""

import base64
import struct
import zlib

from mcp.server.fastmcp import FastMCP
from mcp.types import ImageContent, ResourceLink

mcp = FastMCP(
    "Dummy Artifact Server",
    host="0.0.0.0",
    port=8000,
    stateless_http=True,
)

# ─── Tiny dependency-free PNG encoder (stdlib zlib/struct only) ───────────────

_COLORS = {
    "blue": (30, 80, 220),
    "red": (200, 30, 30),
    "green": (30, 180, 60),
    "yellow": (230, 200, 30),
}


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def make_solid_png(width: int, height: int, rgb: tuple[int, int, int]) -> bytes:
    """Encode a solid-color RGB PNG using only the standard library."""
    signature = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    row = b"\x00" + bytes(rgb) * width  # filter byte 0 (none) + RGB pixels
    raw = row * height
    idat = zlib.compress(raw, 9)
    return (
        signature
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", idat)
        + _png_chunk(b"IEND", b"")
    )


# ─── Resource backing get_sample_report's ResourceLink ────────────────────────

SAMPLE_CSV = "id,label,value\n1,alpha,10\n2,beta,20\n3,gamma,30\n"
SAMPLE_CSV_URI = "resource://dummy/sample-report.csv"


@mcp.resource(SAMPLE_CSV_URI, mime_type="text/csv")
def sample_report_resource() -> str:
    """Backing resource for the ResourceLink returned by get_sample_report."""
    return SAMPLE_CSV


# ─── Tools ─────────────────────────────────────────────────────────────────────


@mcp.tool()
def get_sample_image(color: str = "blue") -> ImageContent:
    """Return a tiny 64x64 solid-color PNG as inline ImageContent."""
    rgb = _COLORS.get(color.lower(), _COLORS["blue"])
    png_bytes = make_solid_png(64, 64, rgb)
    data = base64.b64encode(png_bytes).decode("ascii")
    return ImageContent(type="image", data=data, mimeType="image/png")


@mcp.tool()
def get_sample_report() -> ResourceLink:
    """Return a ResourceLink to a small CSV report, fetched via resources/read."""
    return ResourceLink(
        type="resource_link",
        name="sample-report.csv",
        uri=SAMPLE_CSV_URI,
        mimeType="text/csv",
        description="A tiny CSV report generated by the dummy MCP server",
    )


@mcp.tool()
def get_text_summary() -> str:
    """Return plain text with no attachments (control case: must pass through)."""
    return "This is a plain text summary with no attachments."


if __name__ == "__main__":
    mcp.run(transport="streamable-http")
